#ifndef __JSTP_GEN_H_
#define __JSTP_GEN_H_

/**
 *    This code was generated by JSTP CodeGen version 1.11.0.26193
 *
 *    Generate info:
 *        Date      : 07.12.2017 13:54
 *        User      : voloshkevich
 *        Domain    : NPORTS
 *	Paths:
 *
 *		======== Генератор для дрона ========
 *    	gen: DroneGen 1.0.0
 *        gen.reset : Сброс настроек частоты и мощности
 *        gen.set_freq : Установить частоту
 *        gen.get_freq : Считать частоту в Гц
 *        gen.set_pow : Установить мощность
 *        gen.get_pow : Считать мощность (от 001 до 511) 8,5 единиц ~ 1 дБм
*/

#include "jsmn.h"       // <-- json parser lib (https://bitbucket.org/zserge/jsmn/wiki/Home)
#include "jstp.h"       // <-- json simple text protocol lib

#ifdef __cplusplus
extern "C" {
#endif

int jstp_execute_gen(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count);
int drone_gen_setup();

#ifdef __cplusplus
}
#endif

#endif /* __JSTP_GEN_H_ */
